# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d9dc2bc6c4a1c77f9c0c2c966384cfd2ebfc0d01f7d0e2643b4ba7d5d00dbe939cc631d4bb4acb023ed6cf77ab8bbe68965529a1193554dda323e070a80c2a

test:
  secret_key_base: dc23c8abd2965e56f2117ce8009fc1506121ef197036358533d63951b8b154feb4c3a455f9c66133fa60e99a91c24b16bdbdcb05e7c6896b20005ca81268e7fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
